id: tweets-service
description: Manages tweets in Exosphere applications

messages:
  receives:
    - create
    - list
    - get-details
    - update
    - delete
  sends:
    - created
    - listed
    - details
    - not-found
    - updated
    - deleted

setup: npm install
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port
